version: "3.6" 

services:
  #docker utilisera l'image existante nommée graphql si elle existe , sinon il la construira
  graphql:
   image: graphql
   ports:
     - 4000:4000
   links:
    - "mongo:mongodb"
   build:
     context: graphql
     dockerfile: Dockerfile
   environment:
     - MONGO_URI=mongodb://root:example@mongo:27017

  apache:
    image: php:7.2-apache
    ports:
      - "83:80"
    volumes:
      - ./ui-ventes/:/var/www/html
    build: 
      context: ui-ventes/ #chemin vers le Dockerfile du react
      dockerfile: Dockerfile
    depends_on:
      - graphql
   
  mongo:
    image: mongo:7.0.2
    container_name: mongo-dev
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:1.0.0
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=example

volumes:
  mongodata:
